### ISSUE TITLE
按照脚本训练流程问题

### ISSUE THREAD

**Issue by KIP1024** [wenet-e2e/WenetSpeech#52]
1 我先是按照下载方式中通过魔塔社区下载的数据集，它是自动就给分好train、test等音频数据集，还有一个json文件与切分数据集的名称对应
2 stage 0这一步骤（wenetspeech_data_prep.sh），准备数据部分出现问题，我是把下载数据的json文件放在对应的路径下（但我总感觉不是这个json文件，这个只是对应划分训练集的），执行到下面 3 这个代码时候出现 4 的报错。求解！！没找到有写训练流程的教程。
3   # Files to be created:
  # wav.scp text segments utt2dur
  python3 local/extract_meta.py \
    $wenetspeech_dir/WenetSpeech.json $corpus_dir || exit 1;

4
Traceback (most recent call last):
  File "local/extract_meta.py", line 102, in <module>
    main()
  File "local/extract_meta.py", line 98, in main
    meta_analysis(args.input_json, args.output_dir)
  File "local/extract_meta.py", line 47, in meta_analysis
    if json_data['audio'] is not None:
KeyError: 'audio'

**Comment by Emma-Miao** [comment]
我也遇到了这个，请问怎么解决的呢？
